import "./globals.css";
import { getProviders, signIn } from "next-auth/react";
import { Inter } from "next/font/google";
import { authOptions } from "@/app/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const providers = await getProviders();
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/auth/signin");
    // return (
    //   <>
    //     Not signed in <br />
    //     <button onClick={() => signIn()}>Sign in</button>
    //   </>
    // );
  }

  console.log({ session });

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
